### ISSUE TITLE
Epic 1 : Request for administrative documents

### ISSUE THREAD

**Issue by hjabrail** [Connected-Talent/Connected-Workrers#29]
**SFD - Module 1: Administrative document digitalization**

- [ ] Epic 1: Request for administrative documents
- [ ] Epic 2: Request for authorizations with approval worflow
- [ ] Epic 3: Production Business process related to several modules (clocking in sheet , clocking modification...)
- [ ] Epic 4: Interface, forms and documents related to training
- [ ] Epic 5: Documents to be stored (GED)
